sudo: false
language: go
go:
  - 1.11.x
branches:
  only:
  - master
env:
  - GO111MODULE=on
# before_install:
#   - GO111MODULE=off go get gopkg.in/mikefarah/yq.v2
# addons:
#   apt:
#     update: true
#     packages:
#     - jq
script:
  - ./build.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: opass.app
  local_dir: .build/
  on:
    branch: master
